### ISSUE TITLE
Do you think you can make an adapter for fastapi?

### ISSUE THREAD

**Issue by NickDatLe** [j0ack/flask-inertia#12]
Do you think you can build one? How hard was it?

**Comment by j0ack** [comment]
Hello @NickDatLe, 

It was a nice exercise to build this adapter for Flask and it was not that hard. Unfortunately I am not as familiar with FastAPI internals so I think it would be trickier.

The FastAPI documentation seems to be well documented to [run with custom Middlewares](https://fastapi.tiangolo.com/tutorial/middleware/), which is the way to create an adapter for Inertia.

**Comment by NickDatLe** [comment]
Thanks for replying @j0ack - I'll see what I can do.
I did asked this question in the djanjo adapter github, if you would like to contribute, please join in :)

https://github.com/inertiajs/inertia-django/issues/42
