### ISSUE TITLE
Any plans to support Vite and/or HMR?

### ISSUE THREAD

**Issue by shininglove** [j0ack/flask-inertia#21]
Love this project! Just wanted to know what's the workflow for using it is. I was able to get it to work with Svelte, but struggling to figure out how to make the app refresh on its own when I change files.

**Comment by j0ack** [comment]
Hello thank you for your ticket.

The project is already supporting Vite, there is an opened PR to update the tutorial to configure a project with flask-inertia and vue3-vite: https://github.com/j0ack/flask-inertia/pull/20. 

How did you setup your project with Svelte ? There is an another [repo based on cookiecutter](https://github.com/j0ack/flask-inertia-cookiecutters/) that you can use to configure automatically your dev environments with vue/svelte and react shortly. Feel free to use it or get your config files from it.

**Comment by shininglove** [comment]
Great I'll take a look at the pull request. I saw the cookiecutter repo and used it but it was still using rollup instead of vite so I wanted to see if I could update it to vite. But now I think I can use your vite version and update that then. Thanks!

**Comment by shininglove** [comment]
This was my vite config:

```js
import { defineConfig } from 'vite';

import { svelte } from '@sveltejs/vite-plugin-svelte';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

export default defineConfig(({ mode }) => {
    return {
        build: {
            emptyOutDir: true,
            rollupOptions: {
                input: 'src/main.ts',
                output: {
                    entryFileNames: '[name].js',
                    chunkFileNames: '[name]-[hash].js',
                    assetFileNames: 'bundle.css',
                    dir: '../dist/'
                },
            },
        },
        plugins: [
            svelte({
                preprocess: [vitePreprocess()]
            }),
        ],
        server: {
            cors: mode === "development",
            // hmr: { host: "127.0.0.1", clientPort: 5000}
        },
    }
})
```
and my main.ts:
```js
import { createInertiaApp } from '@inertiajs/svelte'
import "./app.css"

function importPageComponent(name: string, pages: Record<string, any>) {
  // eslint-disable-next-line no-restricted-syntax
  for (const path in pages) {
    if (path.endsWith(`${name.replaceAll(".", "/")}.svelte`)) {
      return typeof pages[path] === "function" ? pages[path]() : pages[path];
    }
  }

  throw new Error(`Page not found: ${name}`);
}

createInertiaApp({
  //@ts-ignore
  resolve: (name) =>
    importPageComponent(name, import.meta.glob("./pages/**/*.svelte")),
  //@ts-ignore
  setup({ el, App, props }) {
    new App({ target: el, props })
  },
})
```

**Comment by shininglove** [comment]
And it seems even with the vue3 vite cookiecutter, you would still need to manually refresh right?

**Comment by shininglove** [comment]
thank you! Just wanted to see if there were plans because I wanted to try combining your package with flask-vite and see if that would work. if it does, I can link it and/or make a pull request if you'd like

**Comment by bonchondev** [comment]
They do actually work pretty well together, here's a template of them together: https://github.com/bonchondev/vite-inertia-flask-template
