### ISSUE TITLE
How to pass additional jinja template context variables?

### ISSUE THREAD

**Issue by AlexJMohr** [j0ack/flask-inertia#23]
My inertia template `inertia_base.html` extends from regular jinja template `base.html` which needs some additional context variables, such as `account`. How can I pass these variables to `render_inertia`? It doesn't seem to support it.

My use case is incremental adoption of inertia/svelte into an existing flask app. I'd like to embed my svelte into an existing hierarchy of jinja templates. Currently It looks like I'd be forced to use an iframe for the svelte app.

**Comment by j0ack** [comment]
Hello Alex. 

May I ask which version of `flask-inertia` do you use ? Since version `0.5` you can use the `view_data` argument in `render_inertia` to add template related context https://flask-inertia.readthedocs.io/en/stable/#root-template-data. You should be able to use it to add variables in tour templates.

**Comment by AlexJMohr** [comment]
I am using v0.9. The problem with `view_data` is I'd have to change my base templates to use `{{ view_data.account }}` instead of just `{{ account }}` for example. Is there another way?

**Comment by j0ack** [comment]
There is no other way to pass context to the template. 

`render_inertia` does not accept `kwargs` arguments that would be used in `render_template`

**Comment by AlexJMohr** [comment]
Thanks for the quick response.

Is there any chance of adding a `context` argument or `**kwargs` to `render_inertia` to support this usecase? `context` would probably be less of a breaking change, but `**kwargs` would parallel the API of `flask.render_template` a bit better.

Personally I'm not a fan of the `view_data` API because it's kind of invasive to the way you have to write your base template.

**Comment by j0ack** [comment]
Sorry, I fail to see why `context` instead of `view_data` would be less invasive in your template code.

Concerning mimicking the `flask.render_template` API, I'm not sure I would support this feature. The API has been designed in the purpose of separating explicitly the inertia and the flask contexts.

**Comment by AlexJMohr** [comment]
> Concerning mimicking the flask.render_template API, I'm not sure I would support this feature. The API has been designed in the purpose of separating explicitly the inertia and the flask contexts.

Totally fair, I agree

> Sorry, I fail to see why context instead of view_data would be less invasive in your template code.

Let me give a better example.

Currently my templates are rendered such as this:

```py
context = {'account': ...}
return render_template('mytemplate.html', **context)
```
```jinja
<div>{{ account.name }}</div>
```

If I use `view_data` with flask-inertia, the template has to be changed:

```py
context = {'account': ...}
return render_inertia('MyComponent', view_data=context)
```
```jinja
<div>{{ view_data.account.name }}</div>
```

Instead, if a context parameter was added to `render_inertia`:

```py
context = {'account': ...}
return render_inertia('MyComponent', context=context)
```
```jinja
<div>{{ account.name }}</div>
```

The difference between `view_data` and `context` would be how they are passed to `flask.render_template`. Here is a diff for example (not tested)

```diff
diff --git a/flask_inertia/views.py b/flask_inertia/views.py
index f245ffd..4bff7ff 100644
--- a/flask_inertia/views.py
+++ b/flask_inertia/views.py
@@ -43,6 +43,7 @@ def render_inertia(
     component_name: str,
     props: Dict[str, Any] = {},
     view_data: Dict[str, Any] = {},
+    context: Dict[str, Any] = {},
 ) -> Response:
     """Method to use instead of Flask `render_template`.
 
@@ -124,6 +125,7 @@ def render_inertia(
         return response
    
    context = {
+       **context,
        "view_data": view_data,
        "page": {
            "version": inertia_version,
            "url": request.url,
            "component": component_name,
            "props": merged_props,
        },
    }

    return render_template(inertia_template, **context)
```

An alternative solution would be to change how `view_data` is passed, to `{**view_data, ...}` instead of `{"view_data": view_data, ...}`. This would obviously be a breaking change, but you wouldn't have both `view_data` and `context`. To be honest I think this is the better way to go, but breaking changes are hard to justify. That said, the version is `0.x` still so now is the time if you were to do it.

Let me know your thoughts, and thanks!

**Comment by j0ack** [comment]
Ok I undestand what you meant.

Your solution would introduce two args for the `render_inertia` method with same purpose : passing args to your templates outside of inertia's context, which I find redundant. As said, the API has been designed to explicitly separate the `inertia` and the `flask` contexts. Adding a new argument to bypass this logic seems unintuitive.

Concerning the alternative solution, as you mentioned it would be a major breaking change concerning how the API was designed. The package version actually mirrored the inertiajs one in its minor revisions and is not a state of the development status at this point (I need to upgrade it to version 1 after revising Inertia changelog).

I will not support change in the `render_inertia` API to support a new way to pass arguments to templates
